# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-17 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(max_length=10)),
                ('student_fname', models.CharField(max_length=20)),
                ('student_lname', models.CharField(max_length=20)),
                ('student_oname', models.CharField(blank=True, max_length=20, null=True)),
                ('student_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=7)),
                ('student_address', models.CharField(max_length=200)),
                ('student_religion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Other', 'Other')], max_length=13)),
                ('student_dob', models.DateTimeField()),
                ('student_clss', models.CharField(max_length=50)),
                ('applicant_phone_no', models.CharField(max_length=11)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_application', models.DateTimeField(auto_now_add=True)),
                ('student_passport', models.ImageField(upload_to='admission/')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Waiting', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='2019 / 2020', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Session'),
        ),
    ]
