# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-17 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineadmission',
            name='admission_id',
            field=models.CharField(default='00000039', max_length=10),
        ),
    ]
