# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20190717_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineadmission',
            name='student_clss',
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='mode_of_entry',
            field=models.CharField(choices=[('DE', 'DE'), ('UTME', 'UTME')], default='UTME', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineadmission',
            name='admission_id',
            field=models.CharField(default='00000037', max_length=10),
        ),
        migrations.AlterField(
            model_name='onlineadmission',
            name='student_dob',
            field=models.DateField(),
        ),
    ]
