# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-17 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20190717_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onlineadmission',
            name='admission_id',
            field=models.CharField(default='00000020', max_length=10),
        ),
    ]
