# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_auto_20190717_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('grade', models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='certificate',
            field=models.CharField(choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('NAPTEB', 'NAPTEB')], default='WAEC', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='pri_from',
            field=models.CharField(default=2009, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='pri_school_attended',
            field=models.CharField(default='Sangere Community', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='pri_to',
            field=models.CharField(default='2019', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='sec_from',
            field=models.CharField(default='100', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='sec_school_attended',
            field=models.CharField(default='kkl', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='sec_to',
            field=models.CharField(default='op', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineadmission',
            name='admission_id',
            field=models.CharField(default='00000027', max_length=10),
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.SubjectGrade'),
            preserve_default=False,
        ),
    ]
