# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-17 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_auto_20190717_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineadmission',
            name='student',
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.OnlineAdmission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineadmission',
            name='admission_id',
            field=models.CharField(default='00000044', max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='grade',
            field=models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2),
        ),
    ]
